DROP TABLE IF EXISTS `vtcalendar`.`vtcal_colors`;
CREATE TABLE  `vtcalendar`.`vtcal_colors` (
  `calendarid` varchar(50) NOT NULL,

  `BG` char(7) NOT NULL,
  `Text` char(7) NOT NULL,
  `Text_Faded` char(7) NOT NULL,
  `Text_Warning` char(7) NOT NULL,
  `Link` char(7) NOT NULL,
  `Body` char(7) NOT NULL,
  `Today` char(7) NOT NULL,
  `TodayLight` char(7) NOT NULL,
  `Light_Cell_BG` char(7) NOT NULL,
  `Table_Header_Text` char(7) NOT NULL,
  `Table_Header_BG` char(7) NOT NULL,
  `Border` char(7) NOT NULL,
  `Keyword_Highlight` char(7) NOT NULL,
  `H2` char(7) NOT NULL,
  `H3` char(7) NOT NULL,
  `Title` char(7) NOT NULL,
  `TabGrayed` char(7) NOT NULL,
  `FilterNotice_BG` char(7) NOT NULL,
  `FilterNotice_Font` char(7) NOT NULL,
  `FilterNotice_FontFaded` char(7) NOT NULL,
  `FilterNotice_BGImage` char(7) NOT NULL,
  `Eventbar_Past` char(7) NOT NULL,
  `Eventbar_Current` char(7) NOT NULL,
  `Eventbar_Future` char(7) NOT NULL,
  `MonthDayLabels_Past` char(7) NOT NULL,
  `MonthDayLabels_Current` char(7) NOT NULL,
  `MonthDayLabels_Future` char(7) NOT NULL,
  `OtherMonth` char(7) NOT NULL,
  `LittleCal_Today` char(7) NOT NULL,
  `LittleCal_Highlight` char(7) NOT NULL,
  `LittleCal_Fontfaded` char(7) NOT NULL,
  `LittleCal_Line` char(7) NOT NULL,
  `GOBtn_BG` char(7) NOT NULL,
  `GOBtn_Border` char(7) NOT NULL,

  PRIMARY KEY  (`calendarid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;